// Last modified: 6/20/2020 2:38:58 PM
#define IDH_R_GP_MAINFRAME                      0x20010
#define IDH_R_GSCNTYPE                          0x20011
#define IDH_R_GAMETYPE                          0x20012
#define IDH_R_GP_BOARDVIEW                      0x20013
#define IDH_R_GMOVTYPE                          0x20014
#define IDH_R_BOGUS                             0x207E4
#define IDH_R_MENU_PLAYER_POPUPS                0x207E7
#define IDH_R_HOLDER                            0x207EC
#define IDH_R_TBAR_PLAYBACK                     0x207FD
#define IDH_R_TBAR_VIEW                         0x20803
#define IDH_R_TBAR_MOVE                         0x20805
#define IDH_PROJITEM_DELETE                     0x18042
#define IDH_SCN_SELPIECES                       0x19C40
#define IDH_SCN_BOARDSEL                        0x19C41
#define IDH_SCN_TRAYS                           0x19C42
#define IDH_SCN_PROPERTIES                      0x19C43
#define IDH_VIEW_BOARD                          0x19C44
#define IDH_VIEW_TRAYA                          0x19C45
#define IDH_VIEW_TRAYB                          0x19C46
#define IDH_VIEW_MARKERPAL                      0x19C47
#define IDH_VIEW_FULLSCALEBRD                   0x19C48
#define IDH_VIEW_HALFSCALEBRD                   0x19C49
#define IDH_EDIT_SETBOOKMARK                    0x19C4A
#define IDH_EDIT_RESTOREBOOKMARK                0x19C4B
#define IDH_VIEW_ANNOTATIONS                    0x19C4C
#define IDH_VIEW_PIECES                         0x19C4D
#define IDH_ACT_TOFRONT                         0x19C4E
#define IDH_ACT_TOBACK                          0x19C4F
#define IDH_ACT_STACK                           0x19C52
#define IDH_ACTIONS_ANNWITHTEXT                 0x19C53
#define IDH_ACT_DRAWLINE                        0x19C54
#define IDH_ACT_DRAWTEXTBOX                     0x19C55
#define IDH_ACT_DOMESSAGE                       0x19C56
#define IDH_EDIT_CLRBOOKMARK                    0x19C57
#define IDH_VIEW_DICEPAL                        0x19C58
#define IDH_ACT_TURNOVER                        0x19C59
#define IDH_ACT_ROTATE                          0x19C5A
#define IDH_ACT_REFINESELECT                    0x19C5B
#define IDH_ACT_ARRANGESTACK                    0x19C5C
#define IDH_DEBUG_MOVELIST                      0x19C5D
#define IDH_PBCK_START                          0x19C5E
#define IDH_PBCK_NEXT                           0x19C5F
#define IDH_PBCK_PREVIOUS                       0x19C60
#define IDH_PBCK_END                            0x19C61
#define IDH_PBCK_DISCARD                        0x19C62
#define IDH_PBCK_FINISH                         0x19C63
#define IDH_ACT_PLOTDONE                        0x19C64
#define IDH_ACT_PLOTDISCARD                     0x19C65
#define IDH_PBCK_READMESSAGE                    0x19C66
#define IDH_INDICATOR_CELLNUM                   0x19C67
#define IDH_VIEW_SNAPGRID                       0x19C68
#define IDH_EDIT_SELALLMARKERS                  0x19C69
#define IDH_PLAYBACK_NEXTHISTORYENTRY           0x19C79
#define IDH_PBCK_NEXTHIST                       0x19C7A
#define IDH_PBCK_CLOSEHIST                      0x19C7B
#define IDH_FILE_SENDMOVES2FILE                 0x19C7C
#define IDH_FILE_DISCARDRECORDING               0x19C7D
#define IDH_EDIT_SELECTBOARDS                   0x19C7E
#define IDH_EDIT_CREATETRAY                     0x19C7F
#define IDH_EDIT_SELECTGAMEPIECES               0x19C80
#define IDH_EDIT_SCNPROPERTIES                  0x19C81
#define IDH_VIEW_TOGGLESCALE                    0x19C82
#define IDH_FILE_LOADMOVES                      0x19C83
#define IDH_EDIT_BRD2FILE                       0x19C84
#define IDH_EDIT_BRDPROP                        0x19C85
#define IDH_ACT_COMPOUNDMOVE_BEGIN              0x19C86
#define IDH_ACT_COMPOUNDMOVE_END                0x19C87
#define IDH_ACT_COMPOUNDMOVE_DISCARD            0x19C88
#define IDH_INDICATOR_COMPMOVE                  0x19C89
#define IDH_ACT_ROTATEREL                       0x19C8A
#define IDH_PPROJITEM_PROPERTIES                0x19C8B
#define IDH_PPROJITEM_DELETE                    0x19C8C
#define IDH_PPROJITEM_EDIT                      0x19C8D
#define IDH_PPROJITEM_VIEW                      0x19C8E
#define IDH_PPROJITEM_REPLAY                    0x19C8F
#define IDH_PPROJITEM_EXPORT                    0x19C90
#define IDH_ACT_ROTATEGROUP                     0x19C91
#define IDH_PTOOL_SELECT                        0x19CA4
#define IDH_PTOOL_LINE                          0x19CA5
#define IDH_PTOOL_TEXTBOX                       0x19CA6
#define IDH_PTOOL_PLOTMOVE                      0x19CA7
#define IDH_FILE_SAVE_GAME_AS_SCENARIO          0x19CAF
#define IDH_DEBUG_PIECETABLE                    0x19CB0
#define IDH_ACTIONS_ROLLDICE                    0x19CB1
#define IDH_VIEW_DRAW_IND_ON_TOP                0x19CB2
#define IDH_PBCK_STEP_CMOVES                    0x19CB3
#define IDH_PTRAY_SHUFFLE                       0x19CB4
#define IDH_VIEW_SPLITBOARDROWS                 0x19CB5
#define IDH_VIEW_SPLITBOARDCOLS                 0x19CB6
#define IDH_EDIT_IMPORTPCEGROUPS                0x19CB7
#define IDH_VIEW_SHOW_TIP_TEXT                  0x19CB9
#define IDH_EDIT_ELEMENT_TEXT                   0x19CBA
#define IDH_ACT_LOCKOBJECT                      0x19CC2
#define IDH_ACT_LOCK_SUSPEND                    0x19CC3
#define IDH_VIEW_SAVE_WIN_STATE                 0x19CC4
#define IDH_PTRAY_SHUFFLE_SELECTED              0x19CC5
#define IDH_ACT_SHUFFLE_SELECTED                0x19CC7
#define IDH_ACT_AUTOSTACK_DECK                  0x19CC8
#define IDH_ACT_SHUFFLE_AND_STACK               0x19CC9
#define IDH_EDIT_CREATE_PLAYERS                 0x19CCA
#define IDH_EDIT_EDIT_PLAYERS                   0x19CCB
#define IDH_ACT_TAKE_OWNERSHIP                  0x19CCC
#define IDH_ACT_RELEASE_OWNERSHIP               0x19CCD
#define IDH_ACT_SET_OWNER                       0x19CCE
#define IDH_ACT_TURNOVER_ALL                    0x19CCF
#define IDH_ACT_SIMULATE_SPECTATOR              0x19CD0
#define IDH_EDIT_CREATE_GEOMORPHIC              0x19CD1
#define IDH_HELP_WEBSITE                        0x19CD2
#define IDH_HELP_DONATION                       0x19CD3
#define IDH_PTRAY_ABOUT                         0x19CD4
#define IDH_FILE_CREATE_REFEREE                 0x19CD5
#define IDH_PBCK_STEP_TO_NEXT_HIST              0x19CD6
#define IDH_PBCK_SKIP_KEEP_IND                  0x19CD7
#define IDH_PBCK_AUTO_STEP                      0x19CD8
#define IDH_VIEW_SHOW_TIP_OWNER                 0x19CD9
#define IDH_VIEW_SMALLSCALEBRD                  0x19CDC
#define IDH_VIEW_BOARD_ROTATE180                0x19CDD
#define IDH_FILE_CHANGE_GAME_OWNER              0x19CDE
#define IDH_ACT_ROTATE_0                        0x19D6C
#define IDH_ACT_ROTATE_30                       0x19D72
#define IDH_ACT_ROTATE_45                       0x19D75
#define IDH_ACT_ROTATE_60                       0x19D78
#define IDH_ACT_ROTATE_90                       0x19D7E
#define IDH_ACT_ROTATE_120                      0x19D84
#define IDH_ACT_ROTATE_135                      0x19D87
#define IDH_ACT_ROTATE_150                      0x19D8A
#define IDH_ACT_ROTATE_180                      0x19D90
#define IDH_ACT_ROTATE_210                      0x19D96
#define IDH_ACT_ROTATE_225                      0x19D99
#define IDH_ACT_ROTATE_240                      0x19D9C
#define IDH_ACT_ROTATE_270                      0x19DA2
#define IDH_ACT_ROTATE_300                      0x19DA8
#define IDH_ACT_ROTATE_315                      0x19DAB
#define IDH_ACT_ROTATE_330                      0x19DAE
