//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cbdesign.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   2
#define IDR_GAMEBOX                     3
#define IDR_BOARDVIEW                   4
#define IDR_BITEDITOR                   5
#define IDS_RESOURCE_VERSION            100
#define IDS_ERR_RESOURCE_VERSION        101
#define IDS_BASEFONT_NAME               102
#define IDS_BASEFONT_SIZE_SMALL         103
#define IDS_BASEFONT_SIZE_BIG           104
#define IDS_BETA_VERSION                110
#define IDS_TILEINUSE                   128
#define IDS_ERR_BOARDNAME               129
#define IDS_ERR_NOTAGAMEBOX             130
#define IDS_ERR_GAMEBOXNEWER            131
#define IDS_ERR_PIECESETSIZE            132
#define IDP_DELETEBOARD                 133
#define IDP_DELETETILESET               134
#define IDP_DELETEPIECESET              135
#define IDP_DELETEMARKSET               136
#define IDS_ERR_VIDEORES                137
#define IDS_WARN_RESHAPE                138
#define IDS_ERR_TILESETNAME             139
#define IDS_ERR_PIECESETNAME            140
#define IDS_ERR_MARKERSETNAME           141
#define IDP_PROGVER                     142
#define IDP_FILEVER                     143
#define IDS_ERR_BOARDSIZE               144
#define IDS_BTN_CREATE                  145
#define IDS_BTN_PROPERTIES              146
#define IDS_BTN_EDIT                    147
#define IDS_BTN_DELETE                  148
#define IDS_BTN_CLONE                   149
#define IDS_BTN_NEW                     150
#define IDS_PHEAD_BOARDS                151
#define IDS_PHEAD_TILES                 152
#define IDS_PHEAD_PIECES                153
#define IDS_PHEAD_MARKS                 154
#define IDS_PHEAD_DOCTYPE               155
#define IDS_ERR_NEEDONEOBJECT           156
#define IDP_ERR_MINCOLORS               157
#define IDP_ERR_EXPIRED                 158
#define IDP_ERR_ALMOSTEXPIRED           159
#define IDS_BMP_FILTER                  160
#define IDP_ERR_LOADBITMAP              161
#define IDS_SEL_BITMAPFILE              162
#define IDS_GTL_FILTER                  163
#define IDS_SEL_LOADTILELIBRARY         164
#define IDP_ERR_NOTGTLB                 165
#define IDP_ERR_GTLBVERSION             166
#define IDP_ERR_GTLBREAD                167
#define IDP_ERR_GTLBWRITE               168
#define IDS_SEL_SAVETILELIBRARY         169
#define IDP_ERR_GTLBCREATE              170
#define IDP_WARN_CHGID                  171
#define IDP_WARN_CHGID2                 172
#define IDS_PROJTYPE_GAMEBOX            173
#define IDS_TT_NULLCOLOR                174
#define IDS_TT_TRANSCOLOR               175
#define IDS_TT_COLORCELLS               176
#define IDS_BSIZE_PATTERN               177
#define IDS_BSIZE_INVALID               178
#define IDS_COPY_OF                     179
#define IDS_COMPRESS_NONE               180
#define IDS_COMPRESS_FASTEST            181
#define IDS_COMPRESS_MEDIUM             182
#define IDS_COMPRESS_MOST               183
#define IDS_ERR_BAD_PASSWORD            184
#define IDS_ERR_NEED_PASSWORD           185
#define IDS_WARN_PASS_MUST_MATCH        186
#define IDS_TIP_PREFIX_FRONT            187
#define IDS_TIP_PREFIX_BACK             188
#define IDS_TIP_LBOXITEM_MARKER         189
#define IDS_URL_CB_WEBSITE              190
#define IDS_URL_CB_DONATION             191
#define IDS_WARN_FILE_UPGRADE           192
#define IDS_ERR_SAVE_DELETE_FAIL        193
#define IDS_TT_CUST_COLOR_CELLS         194
#define IDS_TT_LINEWIDTH_COMBO          195
#define IDS_SIDE_N                      196
#define IDD_GM_ABOUTBOX                 1000
#define IDD_BRDNEW                      1002
#define IDD_TILESETNEW                  1005
#define IDD_ENTERNUM                    1006
#define IDB_SYSBUTTON                   1007
#define IDB_50PERCENT                   1008
#define IDC_NODROP                      1009
#define IDB_25PERCENT                   1011
#define IDC_DRAGTILE                    1013
#define IDC_CROSSHAIR                   1014
#define IDB_DRAWLAYERTOOLS              1015
#define IDC_ERASER                      1016
#define IDB_IMAGETOOLS                  1017
#define IDD_TEXTPROP                    1018
#define IDD_PIECEFACTORY                1020
#define IDD_NEWTILE                     1021
#define IDD_MASKBOARD                   1022
#define IDD_GBOXPROP                    1023
#define IDD_TILESETPROP                 1024
#define IDC_BRUSH                       1025
#define IDD_BRDPRP                      1026
#define IDC_DROPPER                     1028
#define IDC_FILL                        1029
#define IDC_PENCIL                      1030
#define IDI_OMMMMMM                     1031
#define IDD_SETSCALEVISIBILITY          1033
#define IDD_PIECEEDIT                   1034
#define IDC_SMALL4WAY                   1034
#define IDD_BRDRESHAPE                  1035
#define IDD_TILERESIZE                  1036
#define IDD_PIECENEWGRP                 1037
#define IDD_MARKERNEWGRP                1038
#define IDD_PIECEGRPPROP                1039
#define IDD_MARKERGRPPROP               1040
#define IDD_MARKERFACTORY               1041
#define IDD_MARKEREDIT                  1042
#define IDD_PASTE                       1043
#define IDC_COLORCHANGE                 1047
#define IDD_ENTER_PASSWORD              1048
#define IDD_SET_PASSWORD                1049
#define IDD_PIECE_EDIT_MULTIPLE         1050
#define IDD_MARKER_EDIT_MULTIPLE        1051
#define IDR_MENU_DESIGN_POPUPS          2023
#define IDC_D_ABOUT_FILEVER             5001
#define IDC_D_ABOUT_GENDATE             5002
#define IDC_D_ABOUT_VERSION             5003
#define IDC_D_BRDMSK_BOARDS             5004
#define IDC_D_ABOUT_GENDATE2            5004
#define IDC_D_BRDPRP_BOARDNAME          5005
#define IDC_D_BRDPRP_BORDERTOP          5006
#define IDC_D_BRDPRP_CELLBORDER         5007
#define IDC_D_BRDPRP_CELLCOLOR          5008
#define IDC_D_BRDPRP_COLS               5009
#define IDC_D_BRDPRP_HEIGHT             5010
#define IDC_D_BRDPRP_INVCOLS            5011
#define IDC_D_BRDPRP_INVROWS            5012
#define IDC_D_BRDPRP_RESHAPE            5013
#define IDC_D_BRDPRP_ROWS               5014
#define IDC_D_BRDPRP_SNAPON             5015
#define IDC_D_BRDPRP_TRACK              5016
#define IDC_D_BRDPRP_TRKCOFF            5017
#define IDC_D_BRDPRP_TRKROFF            5018
#define IDC_D_BRDPRP_TRKSTYLE           5019
#define IDC_D_BRDPRP_WIDTH              5020
#define IDC_D_BRDPRP_XOFFSET            5021
#define IDC_D_BRDPRP_XPIXELS            5022
#define IDC_D_BRDPRP_YOFFSET            5023
#define IDC_D_BRDPRP_YPIXELS            5024
#define IDC_D_BRDSHP_CELLHT             5025
#define IDC_D_BRDPRP_PXLHEIGHT          5025
#define IDC_D_BRDSHP_CELLWD             5026
#define IDC_D_BRDPRP_PXLWIDTH           5026
#define IDC_D_BRDSHP_COLS               5027
#define IDC_D_BRDPRP_XPARENTCELLS       5027
#define IDC_D_BRDSHP_ROWS               5028
#define IDC_D_BRDSHP_STAGGERIN          5029
#define IDC_D_BRDPRP_HALF_PXLWIDTH      5029
#define IDC_D_CRTGRP_TSETNAME           5030
#define IDC_D_BRDPRP_SMALL_PXLWIDTH     5030
#define IDC_D_ENTNUM_NUMBER             5031
#define IDC_D_BRDPRP_SMALL_PXLHEIGHT    5031
#define IDC_D_ENTNUM_PROMPTTEXT         5032
#define IDC_D_BRDPRP_HALF_PXLHEIGHT     5032
#define IDC_D_GBXPRP_AUTHOR             5033
#define IDC_D_GBXPRP_DESCR              5034
#define IDC_D_GBXPRP_GAMEID             5035
#define IDC_D_GBXPRP_TITLE              5036
#define IDC_D_MARKGRP_NAME              5037
#define IDC_D_MCREATE_CREATE            5038
#define IDC_D_MCREATE_MARKERS           5039
#define IDC_D_MCREATE_TILES             5040
#define IDC_D_MCREATE_TSET              5041
#define IDC_D_MEDIT_MARKERS             5042
#define IDC_D_MEDIT_TILES               5043
#define IDC_D_MEDIT_TSET                5044
#define IDC_D_NEWBRD_BOARDNAME          5045
#define IDC_D_NEWBRD_CELLHEIGHT         5046
#define IDC_D_NEWBRD_CELLWIDTH          5047
#define IDC_D_NEWBRD_GRIDCOLS           5048
#define IDC_D_NEWBRD_GRIDROWS           5049
#define IDC_D_NEWBRD_HBRICK             5050
#define IDC_D_NEWBRD_HEXFLAT            5051
#define IDC_D_NEWBRD_HEXPNT             5052
#define IDC_D_NEWBRD_RECT               5053
#define IDC_D_NEWBRD_STAGGERIN          5054
#define IDC_D_NEWBRD_VBRICK             5055
#define IDC_D_NTILE_BOARDNAME           5056
#define IDC_D_NTILE_HEIGHT              5057
#define IDC_D_NTILE_WIDTH               5058
#define IDC_D_PCREATE_BTILE             5060
#define IDC_D_PCREATE_BTSET             5061
#define IDC_D_PCREATE_FTILE             5062
#define IDC_D_PCREATE_FTSET             5063
#define IDC_D_PCREATE_PIECES            5064
#define IDC_D_PEDIT_BACK                5065
#define IDC_D_PEDIT_BTILE               5066
#define IDC_D_PEDIT_BTSET               5067
#define IDC_D_PEDIT_FTILE               5068
#define IDC_D_PEDIT_FTSET               5069
#define IDC_D_PEDIT_PIECE               5070
#define IDC_D_PGRP_NAME                 5071
#define IDC_D_PIECEGRP_NAME             5072
#define IDC_D_PIECE_CREATE              5073
#define IDC_D_PIECE_QTY                 5074
#define IDC_D_RETILE_BOARDNAME          5075
#define IDC_D_RETILE_CURHT              5076
#define IDC_D_RETILE_CURWD              5077
#define IDC_D_RETILE_RESCALE            5078
#define IDC_D_RETILE_TILEHT             5079
#define IDC_D_RETILE_TILEWD             5080
#define IDC_D_TGRP_NAME                 5081
#define IDC_D_TGRP_TRANSCOLOR           5082
#define IDC_D_TXTPRP_FONT               5083
#define IDC_D_TXTPRP_TEXT               5084
#define IDC_V_GBOXDOC_DELETEOBJECT      5085
#define IDC_V_GBOXDOC_DOCOBJECTS        5086
#define IDC_V_GBOXDOC_EDITOBJECT        5087
#define IDC_V_GBOXDOC_GROUPLIST         5088
#define IDC_V_GBOXDOC_NEWOBJECT         5089
#define IDC_V_GBOXDOC_OBJPROP           5090
#define IDC_V_MMGR_CREATEMARKS          5091
#define IDC_V_MMGR_DELETEMARK           5092
#define IDC_V_MMGR_EDITMARK             5093
#define IDC_V_MMGR_MARKS                5094
#define IDC_V_MMGR_MSETS                5095
#define IDC_V_PMGR_CREATEPIECES         5096
#define IDC_V_PMGR_DELETEPIECE          5097
#define IDC_V_PMGR_EDITPIECE            5098
#define IDC_V_PMGR_PIECES               5099
#define IDC_V_PMGR_PSETS                5100
#define IDC_V_TMGR_CLONETILE            5101
#define IDC_V_TMGR_DELETETILE           5102
#define IDC_V_TMGR_EDITTILE             5103
#define IDC_V_TMGR_NEWTILE              5104
#define IDC_V_TMGR_TILELIST             5105
#define IDC_V_TMGR_TSETNAMELIST         5106
#define IDC_W_TPAL_TSETS                5107
#define IDC_V_BTN_PRJA                  5108
#define IDC_V_BTN_PRJB                  5109
#define IDC_V_BTN_ITMA                  5110
#define IDC_V_BTN_ITMB                  5111
#define IDC_V_BTN_ITMC                  5112
#define IDC_V_BTN_ITMD                  5113
#define IDC_V_PROJLIST                  5114
#define IDC_V_TILELIST                  5115
#define IDC_V_PIECELIST                 5116
#define IDC_V_MARKLIST                  5117
#define IDC_V_EDITINFO                  5118
#define IDC_D_SETVISI_FULL              5120
#define IDC_D_SETVISI_HALF              5121
#define IDC_D_SETVISI_SMALL             5122
#define IDC_D_PASTE_KEEPSIZE            5123
#define IDC_D_PASTE_RESIZE              5124
#define IDC_W_COLORPAL_LINEWIDTH        5125
#define IDC_D_NEWBRD_PIXSIZE            5126
#define IDC_D_GBXPRP_COMPRESSION        5127
#define IDC_D_GETPASS_PASSWORD          5128
#define IDC_D_SETPASS_PASS_1            5129
#define IDC_D_SETPASS_PASS_2            5130
#define IDC_D_SET_PASSWORD              5130
#define IDC_D_MCREATE_TEXTPROMPT        5132
#define IDC_D_MCREATE_TEXT              5133
#define IDC_D_MEDIT_TEXT                5134
#define IDC_D_MEDIT_TEXTPROMPT          5135
#define IDC_D_PCREATE_TEXT_FRONT        5136
#define IDC_D_PCREATE_TEXT_BACK         5137
#define IDC_D_PCREATE_TEXT_SAMEASTOP    5138
#define IDC_D_PEDIT_TEXT_FRONT          5139
#define IDC_D_PEDIT_TEXT_SAMEASTOP      5140
#define IDC_D_PEDIT_TEXT_BACK           5141
#define IDC_D_PEDIT_TOP_VISIBLE         5142
#define IDC_D_PCREATE_TOP_VISIBLE       5143
#define IDC_D_PEDIT_CHG_TOP_TEXT        5145
#define IDC_D_MPEDIT_CHG_TOP_TEXT       5145
#define IDC_D_PEDIT_CHG_BACK_TEXT       5146
#define IDC_D_MPEDIT_CHG_BACK_TEXT      5146
#define IDC_D_PEDIT_FRONT_LABEL         5147
#define IDC_D_MPEDIT_FRONT_LABEL        5147
#define IDC_D_PEDIT_BACK_LABEL          5148
#define IDC_D_MPEDIT_BACK_LABEL         5148
#define IDC_D_MEDIT_TEXT_LABEL          5149
#define IDC_D_MMEDIT_TEXT_LABEL         5149
#define IDC_D_MEDIT_CHG_TEXT            5150
#define IDC_D_MMEDIT_CHG_TEXT           5150
#define IDC_D_PCREATE_TOP_VISIBLE_OWNERS_TOO 5151
#define IDC_D_PEDIT_TOP_VISIBLE_OWNERS_TOO 5152
#define IDC_D_MPEDIT_TOP_VISIBLE        5153
#define IDC_D_MPEDIT_TOP_VISIBLE_OWNERS_TOO 5154
#define IDC_D_MPEDIT_TEXT_FRONT         5155
#define IDC_D_MPEDIT_TEXT_BACK          5156
#define IDC_D_MMEDIT_TEXTPROMPT         5157
#define IDC_D_MMEDIT_TEXT               5158
#define IDC_D_SETVISI_NATURAL           5159
#define IDC_NUM_SIDES                   5162
#define IDC_CURR_SIDE                   5163
#define IDC_STATIC_SIDE_1               5164
#define IDC_D_MARKGRP_VIZFULL           7090
#define IDC_D_MARKGRP_RAND_VIZHIDDEN    7092
#define IDC_D_MARKGRP_RAND_VIZALLHIDDEN 7093
#define ID_OFFSCREEN                    32768
#define ID_EDIT_COLORDLG                32771
#define ID_VIEW_GRIDLINES               32772
#define ID_DEBUG_DUMPPAL                32777
#define ID_EDIT_LAYER_BASE              32782
#define ID_EDIT_LAYER_TILE              32783
#define ID_EDIT_LAYER_TOP               32784
#define ID_WINDOW_TOOLPAL               32785
#define ID_WINDOW_COLORPAL              32786
#define ID_WINDOW_TILEPAL               32787
#define ID_WINDOW_ITOOLPAL              32788
#define ID_DWG_TOFRONT                  32789
#define ID_DWG_TOBACK                   32790
#define ID_DWG_FONT                     32791
#define ID_IMAGE_GRIDLINES              32794
#define ID_IMAGE_UPDATE                 32795
#define ID_IMAGE_DISCARD                32796
#define ID_IMAGE_BOARDMASK              32797
#define ID_VIEW_ZOOMOUT                 32798
#define ID_VIEW_ZOOMIN                  32799
#define ID_VIEW_FULLSCALE               32800
#define ID_VIEW_HALFSCALE               32801
#define ID_VIEW_SMALLSCALE              32802
#define ID_INDICATOR_CELLNUM            32804
#define ID_TOOLS_BRDSNAPGRID            32806
#define ID_TOOLS_BRDPROPS               32807
#define ID_TOOLS_RESIZETILE             32808
#define ID_TOOL_SETVISIBLESCALE         32809
#define ID_TOOL_SUSPENDSCALEVISIBILITY  32811
#define ID_TOOLS_ROT90                  32812
#define ID_TOOLS_ROT180                 32813
#define ID_TOOLS_ROT270                 32814
#define ID_EDIT_GBOXPROPERTIES          32815
#define ID_EDIT_CREATETILEGROUP         32816
#define ID_EDIT_CREATEBOARD             32817
#define ID_EDIT_CREATEPIECEGROUP        32818
#define ID_EDIT_CREATEMARKGROUP         32819
#define ID_EDIT_MOVE                    32820
#define ID_EDIT_PASTEBITMAPFROMFILE     32821
#define ID_PROJECT_SAVETILESINTILELIBRARYFILE 32822
#define ID_PROJECT_SAVETILEFILE         32823
#define ID_PROJECT_LOADTILEFILE         32824
#define ID_PROJECT_CHGID                32825
#define ID_STICKY_DRAWTOOLS             32826
#define ID_TILE_CLONE                   32829
#define ID_TILE_NEW                     32830
#define ID_TILE_DELETE                  32831
#define ID_TILE_EDIT                    32832
#define ID_PROJITEM_PROPERTIES          32833
#define ID_PROJITEM_DELETE              32834
#define ID_PIECE_NEW                    32835
#define ID_PIECE_EDIT                   32836
#define ID_PIECE_DELETE                 32837
#define ID_MARKER_NEW                   32838
#define ID_MARKER_EDIT                  32839
#define ID_MARKER_DELETE                32840
#define ID_DUMP_TILEDATA                32882
#define ID_BUGFIX_DUMPBADTILES          32883
#define ID_EDIT_CLONEBOARD              32884
#define ID_PROJECT_CLONEBOARD           32885
#define ID_DWG_DRAWABOVEGRID            32886
#define ID_URL_DONATION                 32887
#define ID_HELP_DONATION                32888
#define ID_VIEW_TOGGLE_SCALE            32890
#define ID_EXPORT_GAMEBOX               32893
#define ID_TOOL_ARROW                   32900
#define ID_TOOL_ERASER                  32901
#define ID_TOOL_TILE                    32902
#define ID_TOOL_TEXT                    32903
#define ID_TOOL_FILL                    32904
#define ID_TOOL_DROPPER                 32905
#define ID_TOOL_LINE                    32906
#define ID_TOOL_POLYGON                 32907
#define ID_TOOL_RECT                    32908
#define ID_TOOL_OVAL                    32909
#define ID_COLOR_FOREGROUND             32910
#define ID_COLOR_BACKGROUND             32911
#define ID_COLOR_TRANSPARENT            32912
#define ID_COLOR_CUSTOM                 32913
#define ID_LINE_WIDTH                   32914
#define ID_ITOOL_PENCIL                 32920
#define ID_ITOOL_SELECT                 32921
#define ID_ITOOL_BRUSH                  32922
#define ID_ITOOL_FILL                   32923
#define ID_ITOOL_TEXT                   32924
#define ID_ITOOL_LINE                   32925
#define ID_ITOOL_RECT                   32926
#define ID_ITOOL_OVAL                   32927
#define ID_ITOOL_FILLRECT               32928
#define ID_ITOOL_FILLOVAL               32929
#define ID_ITOOL_DROPPER                32930
#define ID_ITOOL_COLORCHANGE            32931
#define ID_HELP_WEBSITE                 40146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1053
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         5165
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
