//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Cbplay.rc
//
#define IDR_GP_MAINFRAME                16
#define IDR_GSCNTYPE                    17
#define IDR_GAMETYPE                    18
#define IDR_GP_BOARDVIEW                19
#define IDR_GMOVTYPE                    20
#define IDS_RESOURCE_VERSION            100
#define IDS_ERR_RESOURCE_VERSION        101
#define IDS_BASEFONT_NAME               102
#define IDS_BASEFONT_SIZE_SMALL         103
#define IDS_BASEFONT_SIZE_BIG           104
#define IDS_BETA_VERSION                110
#define IDS_GBOX_FILTER                 512
#define IDS_GSCN_FILTER                 513
#define IDS_GBOX_SELECT                 514
#define IDS_GSCN_SELECT                 515
#define IDP_PROGVER                     516
#define IDP_GBXVER                      517
#define IDP_GSNVER                      518
#define IDP_GAMVER                      519
#define IDP_GMVVER                      520
#define IDS_ERR_NOTAGAMEBOX             521
#define IDS_ERR_GAMEBOXNEWER            522
#define IDS_ERR_GBXVIDEORES             523
#define IDS_ERR_GBXNOMEM                524
#define IDS_ERR_GBXREAD                 525
#define IDS_ERR_NEEDABOARD              526
#define IDS_ERR_BOARDNOTEXIST           527
#define IDS_ERR_NOBOARDSSELECTED        528
#define IDS_ERR_TRAYHASPIECES           529
#define IDS_TRAYA_TITLE                 530
#define IDS_TRAYB_TITLE                 531
#define IDS_BTN_GSN_SELECT              532
#define IDS_BTN_GSN_VIEW                533
#define IDS_BTN_GSN_PROPERTIES          534
#define IDS_BTN_GSN_REMOVE              535
#define IDS_BTN_GSN_CREATE              536
#define IDS_BTN_GSN_EDIT                537
#define IDS_BTN_GSN_DELETE              538
#define IDS_PHEAD_GSN_BOARDS            539
#define IDS_PHEAD_GSN_TRAYS             540
#define IDS_ERR_TRAYNAME                541
#define IDS_ERR_TRAYNAMEUSED            542
#define IDS_PHEAD_GSN_DOCTYPE           543
#define IDS_ERR_GAMEBOXID               544
#define IDP_ERR_NOGAMEBOX               545
#define IDS_ERR_SCENARIONEWER           546
#define IDS_ERR_NOTASCENARIO            547
#define IDS_ERR_WRONGGAMEBOX            548
#define IDS_ERR_MAJORREV                549
#define IDS_ERR_BOARDMISSING            550
#define IDS_ERR_PIECETBLSIZE            551
#define IDS_BTN_GAM_PROPERTIES          552
#define IDS_BTN_GAM_VIEW                553
#define IDS_BTN_GAM_LOAD                554
#define IDS_BTN_GAM_SAVE                555
#define IDS_BTN_GAM_REPLAY              556
#define IDS_BTN_GAM_EXPORT              557
#define IDS_PHEAD_GAM_DOCTYPE           558
#define IDS_PHEAD_GAM_BOARDS            559
#define IDS_PHEAD_GAM_HISTORY           560
#define IDS_PHEAD_GAM_CURRENT           561
#define IDS_ERR_NOTAGAME                562
#define IDS_ERR_GAMENEWER               563
#define IDS_ERR_WRONGGAME               564
#define IDS_GMOV_FILTER                 565
#define IDS_GMOV_ENTERNAME              566
#define IDS_ERR_NOTAMOVEFILE            567
#define IDS_ERR_HISTSAVE                568
#define IDS_ERR_SAVEASFAIL              569
#define IDS_ERR_FAILEDREVERT            570
#define IDS_GAME_USA_TIMEFMT            571
#define IDS_BTN_GAM_DISCARD             572
#define IDS_PHEAD_GAM_MOVEFILE          573
#define IDS_PMT_RCD_DISCARD             574
#define IDS_ERR_FAILEDRESTORE           575
#define IDS_ERR_FAILEDSTATECHG          576
#define IDS_ERR_FAILEDSTATESAVE         577
#define IDS_BTN_GAM_DONE                578
#define IDS_ERR_NOLOADWHENPLAY          579
#define IDS_ERR_MUSTSAVEB4SAVE          580
#define IDS_ERR_MUSTSAVEB4LOAD          581
#define IDS_PMT_FINISHPLAY              582
#define IDS_MSG_NOGAMESTATE             583
#define IDS_ERR_MISSINGPIECES           584
#define IDS_PHEAD_GAM_HISTPLAY          585
#define IDS_PHEAD_GAM_SUSPEND           586
#define IDS_ERR_NOSAVEWHENPLAY          587
#define IDS_ERR_NODISCARDWHENPLAY       588
#define IDP_ERR_EXPIRED                 589
#define IDP_ERR_ALMOSTEXPIRED           590
#define IDS_BTN_GAM_ACCEPT              591
#define IDS_BMP_FILTER                  592
#define IDS_SEL_BITMAPFILE              593
#define IDP_ERR_BMPWRITE                594
#define IDP_ERR_BMPCREATE               595
#define IDS_PROJTYPE_GAME               596
#define IDS_PROJTYPE_SCENARIO           597
#define IDS_SAVEGAMEASSCENARIO          598
#define IDS_MSG_NOROLLS                 599
#define IDS_BSIZE_INVALID               600
#define IDS_MSG_ROLLWITHSEED            600
#define IDS_MSG_ROLLWITHOUTSEED         601
#define IDS_MSG_ROLLRESULT              602
#define IDS_TRUNCATED                   603
#define IDS_TRAY_HIDDEN                 604
#define IDS_TRAY_RANDHIDDEN             605
#define IDS_TRAY_ALLHIDDEN              606
#define IDS_TRAY_ALLRANDHIDDEN          607
#define IDS_MSG_NOMOVES                 608
#define IDS_MSG_DIVIDER                 609
#define IDS_WARN_DISCARD_COMP_MOVE      610
#define IDS_MSG_ROLLSET                 611
#define IDS_WARN_PIECESDELETED          612
#define IDS_TIP_OBJTEXTCHG              613
#define IDS_TIP_OBJLOCKED               614
#define IDS_TIP_OBJUNLOCKED             615
#define IDS_WARN_DELETEMARKERS          616
#define IDS_TIP_PREFIX_FRONT            617
#define IDS_TIP_PREFIX_BACK             618
#define IDS_TIP_LBOXITEM_MARKER         619
#define IDS_TIP_CLICK_MENU              620
#define IDS_TIP_TRAY_SHUFFLED           621
#define IDS_TIP_OBJS_SHUFFLED           622
#define IDS_TIP_SELLIST_HELP            623
#define IDS_BASE_PLAYER_NAME            624
#define IDS_LBL_NO_OWNER                625
#define IDS_TIP_OWNER_ACQUIRED          626
#define IDS_TIP_OWNER_RELEASED          627
#define IDS_TIP_OWNED_BY_UC             628
#define IDS_TIP_OWNED_BY_LC             629
#define IDS_TIP_OWNED_BY_PROJ           630
#define IDS_GAME_FILTER                 631
#define IDS_GAME_SELECT_ROOT_NAME       632
#define IDS_GAME_SPECTATOR              633
#define IDS_MSG_PLAYER_FILES            634
#define IDS_WARN_PLAYER_FILES_EXIST     635
#define IDS_PHEAD_SPECTATOR_OWNED       636
#define IDS_ERR_PLAYER_TAMPER           637
#define IDS_GAME_REFEREE                638
#define IDS_PHEAD_REFEREE_OWNED         639
#define IDS_INFO_MPLAY_CREATE           640
#define IDS_INFO_MPLAY_CREATE_REF       641
#define IDS_PRJINFO_TITLE               642
#define IDS_PRJINFO_AUTHOR              643
#define IDS_PRJINFO_DESCRIPTION         644
#define IDS_PRJINFO_MPLAYER             645
#define IDS_ROW_BREAK                   646
#define IDS_URL_CB_WEBSITE              647
#define IDS_URL_CB_DONATION             648
#define IDS_TIP_FLIP_RANDOM             648
#define IDS_MSG_TRAY_INFO               649
#define IDS_MSG_TVIZ_ALL_SIDE           650
#define IDS_MSG_TVIZ_ONE_SIDE           651
#define IDS_MSG_TVIZ_HIDDEN             652
#define IDS_MSG_TVIZ_ALL_HIDDEN         653
#define IDS_ERR_TRAY_VIZ                654
#define IDS_MSG_RANDOM_PULL             655
#define IDS_MSG_NOT_OWNED               656
#define IDS_MSG_OWNED_BY                657
#define IDS_MSG_NONOWN_ALLOWED          658
#define IDS_MSG_NONOWN_NOT_ALLOWED      659
#define IDS_MSG_TVIZ_OWNER_TOO          660
#define IDS_MSG_TVIZ_OWNER_FULL         661
#define IDS_WARN_FILE_UPGRADE           662
#define IDS_ERR_INVALID_PASSWORD        663
#define IDS_INFO_REF_CREATED            664
#define IDS_WARN_REF_EXISTS             665
#define IDS_ERR_NOHISTWHENMOVE          666
#define IDS_BARNAME_STANDARD            667
#define IDS_BARNAME_VIEW                668
#define IDS_BARNAME_MOVE                669
#define IDS_BARNAME_PLAYBACK            670
#define IDS_PAL_MARKERS                 671
#define IDS_MESSAGE_WND                 672
#define IDS_INFO_REF_CREATED2           673
#define IDS_INFO_GAME_CREATED           673
#define IDS_TIP_TRAY_FLIPPED_RANDOM     674
#define IDS_MSG_RANDOM_SIDE_PULL        675
#define IDS_ERR_PRIVATE_BOARD_PERM      676
#define IDS_FULLY_HIDDEN_MOVE           677
#define IDS_BOARD_HIDDEN_MOVE           678
#define IDD_ABOUTBOX                    2000
#define IDD_SCNPROP                     2002
#define IDD_PBRDPROP                    2004
#define IDD_SETTRAYS                    2006
#define IDD_SETBOARDS                   2007
#define IDD_VIEWBOARD                   2008
#define IDD_VIEWBOARD_DELETEME          2008
#define IDD_SETPIECES                   2009
#define IDB_SYSBUTTON                   2010
#define IDD_TRAYNEW                     2010
#define IDB_50PERCENT                   2011
#define IDD_TRAYPRP                     2011
#define IDC_NODROP                      2012
#define IDB_25PERCENT                   2013
#define IDC_DRAGTILE                    2014
#define IDC_CROSSHAIR                   2015
#define IDD_GMOVDESCR                   2016
#define IDD_CHOOSESTATE                 2017
#define IDD_SENDMESSAGE                 2018
#define IDD_READMESSAGE                 2019
#define IDR_BOGUS                       2020
#define IDD_ROTATE                      2021
#define IDD_ROTATEPIECE                 2022
#define IDR_MENU_PLAYER_POPUPS          2023
#define IDB_UNUSED                      2025
#define IDD_DIEROLLER                   2027
#define IDR_HOLDER                      2028
#define IDD_TRUNCATE_PLAYBACK           2029
#define IDD_IMPORTPIECEGROUPS           2033
#define IDC_CMOVMODE                    2034
#define IDD_EDIT_ELEMENT_TEXT           2034
#define IDB_MENU_ICON                   2035
#define IDD_CREATE_PLAYERS              2036
#define IDD_EDIT_PLAYERS                2037
#define IDD_MULTIPLAYER_GAME            2038
#define IDD_SELECT_OWNER                2039
#define IDD_GEOMORPHIC_BOARD            2040
#define IDD_MARKER_COUNT                2041
#define IDD_GET_PASSWORD                2042
#define IDD_CHANGE_GAME_OWNER           2043
#define IDR_TBAR_PLAYBACK               2045
#define IDR_TBAR_VIEW                   2051
#define IDR_TBAR_MOVE                   2053
#define IDR_TBMENU                      2057
#define IDC_D_ABOUT_GENDATE2            5004
#define IDC_D_YNEW_NAME                 5072
#define IDC_D_MDESC_DESCR               5119
#define IDC_D_MDESC_TITLE               5120
#define IDC_D_ABOUT_GAMVER              7001
#define IDC_D_ABOUT_GBXVER              7002
#define IDC_D_ABOUT_GMVVER              7003
#define IDC_D_ABOUT_GSNVER              7004
#define IDC_D_ABOUT_PROGVER             7005
#define IDC_D_ABOUT_GENDATE             7006
#define IDC_D_PBRDPROP_BOARDNAME        7007
#define IDC_D_PBPRP_BOARDNAME           7007
#define IDC_D_PBRDPRP_L_CELLBORDER      7008
#define IDC_D_PBPRP_L_CELLBORDER        7008
#define IDC_D_PBRDPRP_PLOT_COLOR        7009
#define IDC_D_PBPRP_PLOTCOLOR           7009
#define IDC_D_PBRDPRP_SNAPON            7010
#define IDC_D_PBPRP_SNAPON              7010
#define IDC_D_PBRDPRP_S_CELLBORDER2     7011
#define IDC_D_PBPRP_S_CELLBORDER        7011
#define IDC_D_PBRDPRP_TRACK             7012
#define IDC_D_PBRDPRP_XOFFSET           7013
#define IDC_D_PBPRP_XOFFSET             7013
#define IDC_D_PBRDPRP_XPCE_STGGR        7014
#define IDC_D_PBPRP_XPCE_STGGR          7014
#define IDC_D_PBRDPRP_XPIXELS           7015
#define IDC_D_PBPRP_XPIXELS             7015
#define IDC_D_PBRDPRP_YOFFSET           7016
#define IDC_D_PBPRP_YOFFSET             7016
#define IDC_D_PBRDPRP_YPCE_STGGR2       7017
#define IDC_D_PBPRP_YPCE_STGGR          7017
#define IDC_D_PBRDPRP_YPIXELS           7018
#define IDC_D_PBPRP_YPIXELS             7018
#define IDC_D_SCNPRP_AUTHOR             7019
#define IDC_D_SCNPRP_DESCR              7020
#define IDC_D_SCNPRP_GAMEID             7021
#define IDC_D_SCNPRP_TITLE              7022
#define IDC_D_SETBRD_LIST               7023
#define IDC_D_SETPCE_COPYALL            7024
#define IDC_D_SETPCE_COPYSEL            7025
#define IDC_D_SETPCE_PCEGRP             7026
#define IDC_D_SETPCE_PCELIST            7027
#define IDC_D_SETPCE_REMALL             7028
#define IDC_D_SETPCE_REMSEL             7029
#define IDC_D_SETPCE_TRAYLIST           7030
#define IDC_D_SETPCE_TRAYNAME           7031
#define IDC_D_SETTRAY_CREATE            7032
#define IDC_D_SETTRAY_DELETE            7033
#define IDC_D_SETTRAY_LIST              7034
#define IDC_D_SETTRAY_TRAYNAME          7035
#define IDC_D_VWBRD_LIST                7036
#define IDC_D_SETTRAY_MODIFY            7037
#define IDC_W_TRAYNAMECOMBO             7038
#define IDC_W_TRAYLIST                  7039
#define IDC_W_MARKNAMECOMBO             7040
#define IDC_W_MARKLIST                  7041
#define IDC_V_GSN_PROJLIST              7042
#define IDC_V_GSN_EDITINFO              7043
#define IDC_V_GSN_TRAYLIST              7044
#define IDC_V_GSN_BTN_PRJA              7045
#define IDC_V_GSN_BTN_PRJB              7046
#define IDC_V_GSN_BTN_PRJC              7047
#define IDC_D_YPRP_NAME                 7048
#define IDC_V_GAM_PROJLIST              7049
#define IDC_V_GAM_BTN_PRJA              7050
#define IDC_V_GAM_BTN_PRJB              7051
#define IDC_V_GAM_EDITINFO              7052
#define IDC_D_STATE_MOVEFILE            7053
#define IDC_D_STATE_CURSTATE            7054
#define IDC_D_SMSG_MESSAGE              7055
#define IDC_D_RMSG_MESSAGE              7056
#define IDC_D_SMSG_MESSAGE2             7056
#define IDC_D_PBPRP_PLOTWIDTH           7057
#define IDC_D_PBPRP_S_RECTCENTER        7058
#define IDC_D_PBPRP_S_SNAPPLOTS         7059
#define IDC_D_ROT_PREVIEW               7059
#define IDC_D_ROT_ANGLE                 7060
#define IDC_D_ROT_APPLY                 7061
#define IDC_D_ROTPCE_CCW5               7062
#define IDC_D_ROTPCE_CCW10              7063
#define IDC_D_ROTPCE_CCW50              7064
#define IDC_D_ROTPCE_CW5                7065
#define IDC_D_ROTPCE_CW10               7066
#define IDC_D_ROTPCE_CW50               7067
#define IDC_D_ROTPCE_CURVAL             7068
#define IDC_DIE_NUMDIES1                7069
#define IDC_D_ROTPCE_CCW1               7069
#define IDC_DIE_ROLL1                   7070
#define IDC_D_ROTPCE_CW1                7070
#define IDC_DIE_FACES1                  7071
#define IDC_DIE_BIAS1                   7072
#define IDC_DIE_BIAS                    7072
#define IDC_DIE_NUMDIES2                7073
#define IDC_DIE_ROLL2                   7074
#define IDC_DIE_FACES2                  7075
#define IDC_DIE_BIAS2                   7076
#define IDC_DIE_NUMDIES3                7077
#define IDC_DIE_ROLL3                   7078
#define IDC_DIE_FACES3                  7079
#define IDC_DIE_BIAS3                   7080
#define IDC_DIE_SEED                    7081
#define IDC_D_SMSG_ROLLDICE             7082
#define IDC_DIE_RESET_SEED              7083
#define IDC_D_TRUNC_DONT                7084
#define IDC_D_TRUNC_DOIT                7085
#define IDC_D_PBPRP_AUTOOPEN            7086
#define IDC_D_YPRP_SHUFFLE              7087
#define IDC_D_YPRP_VIZFULL              7090
#define IDC_D_YPRP_VIZTOP               7091
#define IDC_D_YPRP_VIZHIDDEN            7092
#define IDC_D_YPRP_VIZALLHIDDEN         7093
#define IDC_D_YPRP_RANDSEL              7094
#define IDC_D_PBPRP_SHOW_SEL_AND_TINY   7095
#define IDC_D_YPRP_RANDSIDE             7095
#define IDC_D_SMSG_CLOSE                7096
#define IDC_D_PBPRP_DRAW_LOCKED_BENEATH 7096
#define IDC_D_IMPPCE_GROUPLIST          7097
#define IDC_DIE_SETS                    7098
#define IDC_D_EDITELEM_TEXT             7191
#define IDC_D_CPLAY_NUM_PLAYERS         7192
#define IDC_D_EPLAY_NAME_LIST           7193
#define IDC_D_EPLAY_EDIT_NAME           7194
#define IDC_D_EPLAY_UPDATE_NAME         7195
#define IDC_D_YPRP_OWNER_LIST           7196
#define IDC_D_YPRP_OWNER_LABEL          7197
#define IDC_D_PBPRP_OWNER_LABEL         7198
#define IDC_D_PBPRP_OWNER_LIST          7199
#define IDC_D_YPRP_NONOWNER_ACCESS      7200
#define IDC_D_PBPRP_NONOWNER_ACCESS     7201
#define IDC_D_MPGAME_PLAYER_LIST        7202
#define IDC_D_MPGAME_PLAYER_NAME        7203
#define IDC_D_MPGAME                    7204
#define IDC_D_SELOWN_LIST               7205
#define IDC_D_EDITELEM_SETALL           7206
#define IDC_D_MPGAME_CREATE_REFEREE     7207
#define IDC_D_NEWGEO_BOARD_LIST         7208
#define IDC_D_NEWGEO_GEOMORPHIC_LIST    7209
#define IDC_D_NEWGEO_ADD_BOARD          7210
#define IDC_D_NEWGEO_ADD_BREAK          7211
#define IDC_D_NEWGEO_BOARD_NAME         7212
#define IDC_D_NEWGEO_FLIP_180           7213
#define IDC_D_NEWGEO_CLEAR              7214
#define IDC_D_NEWGEO_UPDATE             7215
#define IDC_D_YPRP_OWNER_TOO            7216
#define IDC_D_NEWGEO_HELP               7217
#define IDC_D_SMSG_SEND                 7218
#define IDC_MRKCNT_NUMBER               7219
#define IDC_D_GETPASS_PASSWORD          7220
#define IDC_D_CHGGAMEOWN_LIST           7221
#define IDC_LIST1                       7222
#define IDC_D_IMPPCE_SELECTALL          7223
#define IDC_D_IMPPCE_CLEARALL           7224
#define IDC_D_SETBRD_SELECTALL          7225
#define IDC_D_SETBRD_CLEARALL           7226
#define IDC_D_PBPRP_NONOWNER_HIDE       7227
#define CTL3D_3DCHECK                   26567
#define ID_PROJITEM_DELETE              32834
#define ID_SCN_SELPIECES                40000
#define ID_SCN_BOARDSEL                 40001
#define ID_SCN_TRAYS                    40002
#define ID_SCN_PROPERTIES               40003
#define ID_VIEW_BOARD                   40004
#define ID_VIEW_TRAYA                   40005
#define ID_VIEW_TRAYB                   40006
#define ID_VIEW_MARKERPAL               40007
#define ID_VIEW_FULLSCALEBRD            40008
#define ID_VIEW_HALFSCALEBRD            40009
#define ID_EDIT_SETBOOKMARK             40010
#define ID_EDIT_RESTOREBOOKMARK         40011
#define ID_VIEW_ANNOTATIONS             40012
#define ID_VIEW_PIECES                  40013
#define ID_ACT_TOFRONT                  40014
#define ID_ACT_TOBACK                   40015
#define ID_ACT_STACK                    40018
#define ID_ACTIONS_ANNWITHTEXT          40019
#define ID_ACT_DRAWLINE                 40020
#define ID_ACT_DRAWTEXTBOX              40021
#define ID_ACT_DOMESSAGE                40022
#define ID_EDIT_CLRBOOKMARK             40023
#define ID_VIEW_DICEPAL                 40024
#define ID_ACT_TURNOVER                 40025
#define ID_ACT_ROTATE                   40026
#define ID_ACT_REFINESELECT             40027
#define ID_ACT_ARRANGESTACK             40028
#define ID_DEBUG_MOVELIST               40029
#define ID_PBCK_START                   40030
#define ID_PBCK_NEXT                    40031
#define ID_PBCK_PREVIOUS                40032
#define ID_PBCK_END                     40033
#define ID_PBCK_DISCARD                 40034
#define ID_PBCK_FINISH                  40035
#define ID_ACT_PLOTDONE                 40036
#define ID_ACT_PLOTDISCARD              40037
#define ID_PBCK_READMESSAGE             40038
#define ID_INDICATOR_CELLNUM            40039
#define ID_VIEW_SNAPGRID                40040
#define ID_EDIT_SELALLMARKERS           40041
#define ID_PLAYBACK_NEXTHISTORYENTRY    40057
#define ID_PBCK_NEXTHIST                40058
#define ID_PBCK_CLOSEHIST               40059
#define ID_FILE_SENDMOVES2FILE          40060
#define ID_FILE_DISCARDRECORDING        40061
#define ID_EDIT_SELECTBOARDS            40062
#define ID_EDIT_CREATETRAY              40063
#define ID_EDIT_SELECTGAMEPIECES        40064
#define ID_EDIT_SCNPROPERTIES           40065
#define ID_VIEW_TOGGLESCALE             40066
#define ID_FILE_LOADMOVES               40067
#define ID_EDIT_BRD2FILE                40068
#define ID_EDIT_BRDPROP                 40069
#define ID_ACT_COMPOUNDMOVE_BEGIN       40070
#define ID_ACT_COMPOUNDMOVE_END         40071
#define ID_ACT_COMPOUNDMOVE_DISCARD     40072
#define ID_INDICATOR_COMPMOVE           40073
#define ID_ACT_ROTATEREL                40074
#define ID_PPROJITEM_PROPERTIES         40075
#define ID_PPROJITEM_DELETE             40076
#define ID_PPROJITEM_EDIT               40077
#define ID_PPROJITEM_VIEW               40078
#define ID_PPROJITEM_REPLAY             40079
#define ID_PPROJITEM_EXPORT             40080
#define ID_ACT_ROTATEGROUP              40081
#define ID_PTOOL_SELECT                 40100
#define ID_PTOOL_LINE                   40101
#define ID_PTOOL_TEXTBOX                40102
#define ID_PTOOL_PLOTMOVE               40103
#define ID_FILE_SAVE_GAME_AS_SCENARIO   40111
#define ID_DEBUG_PIECETABLE             40112
#define ID_ACTIONS_ROLLDICE             40113
#define ID_VIEW_DRAW_IND_ON_TOP         40114
#define ID_PBCK_STEP_CMOVES             40115
#define ID_PTRAY_SHUFFLE                40116
#define ID_VIEW_SPLITBOARDROWS          40117
#define ID_VIEW_SPLITBOARDCOLS          40118
#define ID_EDIT_IMPORTPCEGROUPS         40119
#define ID_VIEW_SHOW_TIP_TEXT           40121
#define ID_EDIT_ELEMENT_TEXT            40122
#define ID_ACT_LOCKOBJECT               40130
#define ID_ACT_LOCK_SUSPEND             40131
#define ID_VIEW_SAVE_WIN_STATE          40132
#define ID_PTRAY_SHUFFLE_SELECTED       40133
#define ID_ACT_SHUFFLE_SELECTED         40135
#define ID_ACT_AUTOSTACK_DECK           40136
#define ID_ACT_SHUFFLE_AND_STACK        40137
#define ID_EDIT_CREATE_PLAYERS          40138
#define ID_EDIT_EDIT_PLAYERS            40139
#define ID_ACT_TAKE_OWNERSHIP           40140
#define ID_ACT_RELEASE_OWNERSHIP        40141
#define ID_ACT_SET_OWNER                40142
#define ID_ACT_TURNOVER_ALL             40143
#define ID_ACT_SIMULATE_SPECTATOR       40144
#define ID_EDIT_CREATE_GEOMORPHIC       40145
#define ID_HELP_WEBSITE                 40146
#define ID_HELP_DONATION                40147
#define ID_PTRAY_ABOUT                  40148
#define ID_FILE_CREATE_REFEREE          40149
#define ID_PBCK_STEP_TO_NEXT_HIST       40150
#define ID_PBCK_SKIP_KEEP_IND           40151
#define ID_PBCK_AUTO_STEP               40152
#define ID_VIEW_SHOW_TIP_OWNER          40153
#define ID_VIEW_SMALLSCALEBRD           40156
#define ID_VIEW_BOARD_ROTATE180         40157
#define ID_FILE_CHANGE_GAME_OWNER       40158
#define ID_ACT_TURNOVER_PREV            40162
#define ID_ACT_TURNOVER_RANDOM          40163
#define ID_ACT_TURNOVER_ALL_PREV        40164
#define ID_ACT_TURNOVER_ALL_RANDOM      40165
#define ID_ACT_TURNOVER_SELECT          40166
#define ID_ACT_ROTATE_0                 40300
#define ID_ACT_ROTATE_30                40306
#define ID_ACT_ROTATE_45                40309
#define ID_ACT_ROTATE_60                40312
#define ID_ACT_ROTATE_90                40318
#define ID_ACT_ROTATE_120               40324
#define ID_ACT_ROTATE_135               40327
#define ID_ACT_ROTATE_150               40330
#define ID_ACT_ROTATE_180               40336
#define ID_ACT_ROTATE_210               40342
#define ID_ACT_ROTATE_225               40345
#define ID_ACT_ROTATE_240               40348
#define ID_ACT_ROTATE_270               40354
#define ID_ACT_ROTATE_300               40360
#define ID_ACT_ROTATE_315               40363
#define ID_ACT_ROTATE_330               40366
#define ID_MRKGROUP_FIRST               40400

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2059
#define _APS_NEXT_COMMAND_VALUE         40166
#define _APS_NEXT_CONTROL_VALUE         7228
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
